spring:
  application:
    name: pinball
  profiles:
    active: dev

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
