spring.application.name=pinball

# Configuración Servidor Web
server.port=7780

# Configuración Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://www.bahatech.cl:7760/TestWS
spring.datasource.username=test_ws
spring.datasource.password=ws78/
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
